// React/src/pages/Recharge.tsx
import React, { useState } from 'react';
import { Crown, CheckCircle2 } from 'lucide-react';
import { motion } from 'framer-motion';

export function Recharge() {
  const [selected, setSelected] = useState(1);
  const user = JSON.parse(localStorage.getItem('user') || '{}');

  const plans = [
    { id: 1, name: '连续包月', price: '19', original: '29', desc: '首月特惠，自动续费' },
    { id: 2, name: '季度会员', price: '58', original: '88', desc: '低至19.3元/月' },
    { id: 3, name: '年度会员', price: '198', original: '348', desc: '低至16.5元/月，最划算' },
  ];

  const handlePay = () => {
    alert('模拟支付成功！您已成为VIP会员。');
    localStorage.setItem('user', JSON.stringify({ ...user, isVip: true }));
    window.location.reload();
  };

  return (
    <div className="bg-gray-50 min-h-full pb-24">
      <div className="bg-[#2C2C2C] px-6 pt-12 pb-20 rounded-b-[40px] shadow-md relative">
        <div className="flex items-center gap-4 text-white">
          <div className="w-14 h-14 bg-gradient-to-br from-yellow-300 to-yellow-600 rounded-full flex items-center justify-center p-1">
            <div className="w-full h-full bg-[#2C2C2C] rounded-full flex items-center justify-center">
              <Crown className="w-6 h-6 text-yellow-400" />
            </div>
          </div>
          <div>
            <h1 className="text-xl font-bold text-yellow-400">{user.name || '同学'}</h1>
            <p className="text-gray-400 text-xs mt-1">
              {user.isVip ? '尊贵的VIP会员，您好！' : '开通VIP，畅享无限次智能批改'}
            </p>
          </div>
        </div>
      </div>

      <div className="px-6 -mt-12 relative z-10">
        <div className="bg-white rounded-2xl p-6 shadow-sm border border-gray-100">
          <h2 className="text-lg font-bold text-gray-800 mb-4">选择会员套餐</h2>
          
          <div className="grid gap-3">
            {plans.map((plan) => (
              <motion.div
                key={plan.id}
                whileTap={{ scale: 0.98 }}
                onClick={() => setSelected(plan.id)}
                className={`relative border-2 rounded-xl p-4 cursor-pointer transition-colors ${
                  selected === plan.id
                    ? 'border-yellow-500 bg-yellow-50/50'
                    : 'border-gray-100 bg-white hover:border-yellow-200'
                }`}
              >
                {selected === plan.id && (
                  <div className="absolute top-0 right-0 bg-yellow-500 text-white text-[10px] font-bold px-2 py-1 rounded-bl-lg rounded-tr-lg">
                    已选
                  </div>
                )}
                <div className="flex justify-between items-center">
                  <div>
                    <h3 className="font-bold text-gray-800">{plan.name}</h3>
                    <p className="text-xs text-gray-500 mt-1">{plan.desc}</p>
                  </div>
                  <div className="text-right">
                    <div className="flex items-baseline gap-1 text-yellow-600 justify-end">
                      <span className="text-sm">¥</span>
                      <span className="text-2xl font-black">{plan.price}</span>
                    </div>
                    <p className="text-[10px] text-gray-400 line-through">¥{plan.original}</p>
                  </div>
                </div>
              </motion.div>
            ))}
          </div>

          <div className="mt-8">
            <h3 className="text-sm font-bold text-gray-800 mb-3">VIP特权</h3>
            <div className="grid grid-cols-2 gap-4">
              <div className="flex items-center gap-2">
                <CheckCircle2 className="w-4 h-4 text-yellow-500" />
                <span className="text-xs text-gray-600">无限次AI批改</span>
              </div>
              <div className="flex items-center gap-2">
                <CheckCircle2 className="w-4 h-4 text-yellow-500" />
                <span className="text-xs text-gray-600">无限次AI帮写</span>
              </div>
              <div className="flex items-center gap-2">
                <CheckCircle2 className="w-4 h-4 text-yellow-500" />
                <span className="text-xs text-gray-600">专属成绩单导出</span>
              </div>
              <div className="flex items-center gap-2">
                <CheckCircle2 className="w-4 h-4 text-yellow-500" />
                <span className="text-xs text-gray-600">优先极速响应</span>
              </div>
            </div>
          </div>

          <button
            onClick={handlePay}
            className="w-full mt-8 bg-gradient-to-r from-yellow-400 to-yellow-600 hover:from-yellow-500 hover:to-yellow-700 text-white font-bold py-3.5 rounded-full shadow-lg shadow-yellow-500/30 transition-all"
          >
            立即开通
          </button>
        </div>
      </div>
    </div>
  );
}

// src/pages/recharge/index.vue
<template>
  <view class="recharge-page">
    <!-- 顶部 VIP 区域 -->
    <view class="vip-header">
      <view class="vip-info">
        <view class="vip-avatar">
          <view class="avatar-inner">
            <wd-icon name="star-on" size="48" color="#eab308" />
          </view>
        </view>
        <view class="vip-text">
          <text class="vip-name">{{ userStore.userName }}</text>
          <text class="vip-status">{{ userStore.isVip ? '尊贵的VIP会员，您好！' : '开通VIP，畅享无限次智能批改' }}</text>
        </view>
      </view>
    </view>

    <!-- 套餐选择 -->
    <view class="plan-area">
      <view class="plan-card">
        <text class="plan-heading">选择会员套餐</text>

        <view class="plan-list">
          <view
            v-for="plan in plans"
            :key="plan.id"
            :class="['plan-item', selected === plan.id ? 'plan-selected' : '']"
            @click="selected = plan.id"
          >
            <view v-if="selected === plan.id" class="selected-badge">
              <text>已选</text>
            </view>
            <view class="plan-row">
              <view>
                <text class="plan-name">{{ plan.name }}</text>
                <text class="plan-desc">{{ plan.desc }}</text>
              </view>
              <view class="plan-price-area">
                <view class="plan-price-row">
                  <text class="currency">¥</text>
                  <text class="plan-price">{{ plan.price }}</text>
                </view>
                <text class="plan-original">¥{{ plan.original }}</text>
              </view>
            </view>
          </view>
        </view>

        <!-- VIP特权 -->
        <view class="privilege-area">
          <text class="privilege-title">VIP特权</text>
          <view class="privilege-grid">
            <view class="privilege-item" v-for="(p, i) in privileges" :key="i">
              <wd-icon name="check" size="28" color="#eab308" />
              <text class="privilege-text">{{ p }}</text>
            </view>
          </view>
        </view>

        <button class="pay-btn" @click="handlePay">立即开通</button>
      </view>
    </view>

    <view style="height: 140rpx;"></view>
    <CustomTabbar />
  </view>
</template>

<script setup>
import { useUserStore } from '@/store/useUserStore'
import CustomTabbar from '@/components/CustomTabbar/index.vue'

const userStore = useUserStore()

const selected = ref(1)

const plans = [
  { id: 1, name: '连续包月', price: '19', original: '29', desc: '首月特惠，自动续费' },
  { id: 2, name: '季度会员', price: '58', original: '88', desc: '低至19.3元/月' },
  { id: 3, name: '年度会员', price: '198', original: '348', desc: '低至16.5元/月，最划算' },
]

const privileges = ['无限次AI批改', '无限次AI帮写', '专属成绩单导出', '优先极速响应']

const handlePay = () => {
  uni.showToast({ title: '模拟支付成功！您已成为VIP会员。', icon: 'none' })
  userStore.setVip(true)
}
</script>

<style scoped lang="scss">
.recharge-page {
  min-height: 100vh;
  background: #f5f5f5;
}

.vip-header {
  background: #2C2C2C;
  padding: 80rpx 40rpx 140rpx;
  border-radius: 0 0 60rpx 60rpx;
}

.vip-info {
  display: flex;
  align-items: center;
  gap: 24rpx;
}

.vip-avatar {
  width: 100rpx;
  height: 100rpx;
  background: linear-gradient(135deg, #fde68a, #d97706);
  border-radius: 50%;
  display: flex;
  align-items: center;
  justify-content: center;
  padding: 4rpx;
}

.avatar-inner {
  width: 100%;
  height: 100%;
  background: #2C2C2C;
  border-radius: 50%;
  display: flex;
  align-items: center;
  justify-content: center;
}

.vip-name {
  font-size: 36rpx;
  font-weight: bold;
  color: #eab308;
  display: block;
}

.vip-status {
  font-size: 22rpx;
  color: #9ca3af;
  margin-top: 6rpx;
  display: block;
}

.plan-area {
  padding: 0 32rpx;
  margin-top: -80rpx;
  position: relative;
  z-index: 10;
}

.plan-card {
  background: #ffffff;
  border-radius: 24rpx;
  padding: 40rpx;
  box-shadow: 0 2rpx 12rpx rgba(0, 0, 0, 0.04);
}

.plan-heading {
  font-size: 32rpx;
  font-weight: bold;
  color: #333333;
  display: block;
  margin-bottom: 24rpx;
}

.plan-list {
  display: flex;
  flex-direction: column;
  gap: 16rpx;
}

.plan-item {
  border: 3rpx solid #f3f4f6;
  border-radius: 20rpx;
  padding: 28rpx;
  position: relative;
  overflow: hidden;
}

.plan-selected {
  border-color: #eab308;
  background: #fffbeb;
}

.selected-badge {
  position: absolute;
  top: 0;
  right: 0;
  background: #eab308;
  padding: 4rpx 16rpx;
  border-radius: 0 0 0 16rpx;
  font-size: 18rpx;
  font-weight: bold;
  color: #ffffff;
}

.plan-row {
  display: flex;
  justify-content: space-between;
  align-items: center;
}

.plan-name {
  font-size: 28rpx;
  font-weight: bold;
  color: #333333;
  display: block;
}

.plan-desc {
  font-size: 22rpx;
  color: #999999;
  margin-top: 6rpx;
  display: block;
}

.plan-price-area {
  text-align: right;
}

.plan-price-row {
  display: flex;
  align-items: baseline;
  gap: 4rpx;
  color: #d97706;
  justify-content: flex-end;
}

.currency {
  font-size: 24rpx;
}

.plan-price {
  font-size: 44rpx;
  font-weight: 900;
}

.plan-original {
  font-size: 20rpx;
  color: #cccccc;
  text-decoration: line-through;
}

.privilege-area {
  margin-top: 48rpx;
}

.privilege-title {
  font-size: 26rpx;
  font-weight: bold;
  color: #333333;
  display: block;
  margin-bottom: 20rpx;
}

.privilege-grid {
  display: flex;
  flex-wrap: wrap;
}

.privilege-item {
  width: 50%;
  display: flex;
  align-items: center;
  gap: 12rpx;
  margin-bottom: 16rpx;
}

.privilege-text {
  font-size: 22rpx;
  color: #666666;
}

.pay-btn {
  width: 100%;
  height: 96rpx;
  background: linear-gradient(90deg, #fbbf24, #d97706);
  border-radius: 48rpx;
  font-size: 32rpx;
  font-weight: bold;
  color: #ffffff;
  border: none;
  margin-top: 48rpx;
  display: flex;
  align-items: center;
  justify-content: center;
  box-shadow: 0 8rpx 24rpx rgba(217, 119, 6, 0.3);
}
</style>
