// React/src/pages/History.tsx
import React from 'react';
import { useNavigate } from 'react-router-dom';
import { ChevronLeft, PenTool, CheckSquare, FileText } from 'lucide-react';

export function History() {
  const navigate = useNavigate();
  const records = JSON.parse(localStorage.getItem('records') || '[]');

  return (
    <div className="min-h-full bg-gray-50 flex flex-col pb-20">
      <div className="bg-white px-4 py-3 flex items-center shadow-sm sticky top-0 z-10">
        <button onClick={() => navigate(-1)} className="p-2 -ml-2 text-gray-600">
          <ChevronLeft className="w-6 h-6" />
        </button>
        <h1 className="text-lg font-bold flex-1 text-center mr-8">历史记录</h1>
      </div>
      <div className="p-4 space-y-3">
        {records.length === 0 ? (
          <div className="text-center text-gray-400 mt-20 flex flex-col items-center">
            <FileText className="w-12 h-12 mb-3 opacity-30" />
            <p>暂无记录</p>
          </div>
        ) : (
          records.map((record: any) => (
            <div 
              key={record.id} 
              onClick={() => navigate(`/record/${record.id}`)}
              className="bg-white p-4 rounded-xl shadow-sm border border-gray-100 flex gap-3 cursor-pointer hover:bg-gray-50 transition-colors"
            >
              <div className={`w-10 h-10 rounded-full flex items-center justify-center shrink-0 ${record.type === 'write' ? 'bg-blue-50 text-blue-500' : 'bg-orange-50 text-orange-500'}`}>
                {record.type === 'write' ? <PenTool className="w-5 h-5" /> : <CheckSquare className="w-5 h-5" />}
              </div>
              <div className="flex-1 min-w-0">
                <div className="flex justify-between items-start mb-1">
                  <h3 className="font-bold text-gray-800 truncate pr-2">{record.title}</h3>
                  <span className="text-[10px] text-gray-400 shrink-0">{record.date}</span>
                </div>
                <p className="text-xs text-gray-500 line-clamp-2">{record.summary}</p>
              </div>
            </div>
          ))
        )}
      </div>
    </div>
  );
}

// src/pages/history/index.vue
<template>
  <view class="history-page">
    <!-- 顶部导航 -->
    <view class="nav-bar">
      <view class="nav-back" @click="goBack">
        <wd-icon name="arrow-left" size="44" color="#666666" />
      </view>
      <text class="nav-title">历史记录</text>
    </view>

    <view class="page-body">
      <view v-if="records.length === 0" class="empty-state">
        <wd-icon name="file" size="96" color="#dddddd" />
        <text class="empty-text">暂无记录</text>
      </view>

      <view v-else class="record-list">
        <view
          v-for="record in records"
          :key="record.id"
          class="record-item"
          @click="goToRecord(record.id)"
        >
          <view :class="['record-icon', record.type === 'write' ? 'blue-bg' : 'orange-bg']">
            <wd-icon :name="record.type === 'write' ? 'edit' : 'check'" size="36" :color="record.type === 'write' ? '#3b82f6' : '#f97316'" />
          </view>
          <view class="record-info">
            <view class="record-top">
              <text class="record-title">{{ record.title }}</text>
              <text class="record-date">{{ record.date }}</text>
            </view>
            <text class="record-summary">{{ record.summary }}</text>
          </view>
        </view>
      </view>
    </view>
  </view>
</template>

<script setup>
import { useRecordStore } from '@/store/useRecordStore'

const recordStore = useRecordStore()
const records = computed(() => recordStore.records)

const goBack = () => {
  uni.navigateBack()
}

const goToRecord = (id) => {
  uni.navigateTo({ url: `/pages/record-detail/index?id=${id}` })
}
</script>

<style scoped lang="scss">
.history-page {
  min-height: 100vh;
  background: #f5f5f5;
}

.nav-bar {
  background: #ffffff;
  padding: 80rpx 32rpx 24rpx;
  display: flex;
  align-items: center;
  box-shadow: 0 2rpx 8rpx rgba(0, 0, 0, 0.04);
  position: sticky;
  top: 0;
  z-index: 10;
}

.nav-back {
  padding: 8rpx;
  margin-left: -16rpx;
}

.nav-title {
  font-size: 34rpx;
  font-weight: bold;
  color: #333333;
  flex: 1;
  text-align: center;
  margin-right: 60rpx;
}

.page-body {
  padding: 24rpx 32rpx;
}

.empty-state {
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  padding-top: 200rpx;
}

.empty-text {
  font-size: 28rpx;
  color: #cccccc;
  margin-top: 20rpx;
}

.record-list {
  display: flex;
  flex-direction: column;
  gap: 16rpx;
}

.record-item {
  background: #ffffff;
  padding: 28rpx;
  border-radius: 20rpx;
  display: flex;
  gap: 20rpx;
  align-items: center;
}

.record-icon {
  width: 72rpx;
  height: 72rpx;
  border-radius: 50%;
  display: flex;
  align-items: center;
  justify-content: center;
  flex-shrink: 0;
}

.blue-bg {
  background: #eff6ff;
}

.orange-bg {
  background: #fff7ed;
}

.record-info {
  flex: 1;
  min-width: 0;
}

.record-top {
  display: flex;
  justify-content: space-between;
  align-items: flex-start;
  margin-bottom: 8rpx;
}

.record-title {
  font-size: 28rpx;
  font-weight: bold;
  color: #333333;
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
  flex: 1;
  padding-right: 16rpx;
}

.record-date {
  font-size: 20rpx;
  color: #cccccc;
  flex-shrink: 0;
}

.record-summary {
  font-size: 22rpx;
  color: #999999;
  overflow: hidden;
  text-overflow: ellipsis;
  display: -webkit-box;
  -webkit-line-clamp: 2;
  -webkit-box-orient: vertical;
}
</style>
