// React/src/pages/RecordDetail.tsx
import React from 'react';
import { useParams, useNavigate } from 'react-router-dom';
import { ChevronLeft, CheckCircle2, AlertCircle } from 'lucide-react';
import ReactMarkdown from 'react-markdown';

export function RecordDetail() {
  const { id } = useParams();
  const navigate = useNavigate();
  const records = JSON.parse(localStorage.getItem('records') || '[]');
  const record = records.find((r: any) => r.id === id);

  if (!record) {
    return (
      <div className="min-h-full bg-gray-50 flex flex-col">
        <div className="bg-white px-4 py-3 flex items-center shadow-sm sticky top-0 z-10">
          <button onClick={() => navigate(-1)} className="p-2 -ml-2 text-gray-600">
            <ChevronLeft className="w-6 h-6" />
          </button>
          <h1 className="text-lg font-bold flex-1 text-center mr-8">记录详情</h1>
        </div>
        <div className="flex-1 flex items-center justify-center text-gray-400">
          记录不存在或已被删除
        </div>
      </div>
    );
  }

  return (
    <div className="min-h-full bg-gray-50 flex flex-col">
      <div className="bg-white px-4 py-3 flex items-center shadow-sm sticky top-0 z-10">
        <button onClick={() => navigate(-1)} className="p-2 -ml-2 text-gray-600">
          <ChevronLeft className="w-6 h-6" />
        </button>
        <h1 className="text-lg font-bold flex-1 text-center mr-8">记录详情</h1>
      </div>

      <div className="flex-1 p-4 overflow-y-auto pb-20">
        {record.type === 'write' ? (
          <div className="bg-white rounded-2xl p-5 shadow-sm border border-gray-100">
            <h2 className="font-bold text-gray-800 mb-2">{record.title}</h2>
            <p className="text-xs text-gray-400 mb-4">{record.date}</p>
            <div className="prose prose-sm max-w-none prose-p:leading-relaxed prose-headings:text-gray-800 text-gray-700">
              <ReactMarkdown>{record.result}</ReactMarkdown>
            </div>
          </div>
        ) : (
          <div className="flex flex-col gap-4">
            {/* Score Card */}
            <div className="bg-white rounded-2xl p-6 shadow-sm border border-gray-100 relative overflow-hidden">
              <div className="absolute -right-4 -top-4 w-24 h-24 bg-orange-50 rounded-full opacity-50" />
              <div className="flex justify-between items-start relative z-10">
                <div>
                  <p className="text-sm text-gray-500 font-medium">学生姓名</p>
                  <h2 className="text-xl font-bold text-gray-800 mt-1">{record.result?.studentName || '未知'}</h2>
                </div>
                <div className="text-right">
                  <p className="text-sm text-gray-500 font-medium">最终得分</p>
                  <div className="flex items-baseline gap-1 text-orange-500">
                    <span className="text-4xl font-black">{record.result?.score || 0}</span>
                    <span className="text-sm font-bold">分</span>
                  </div>
                </div>
              </div>
              
              <div className="mt-6 pt-4 border-t border-gray-100">
                <h3 className="text-sm font-bold text-gray-800 mb-2 flex items-center gap-1.5">
                  <CheckCircle2 className="w-4 h-4 text-green-500" />
                  老师评语
                </h3>
                <p className="text-sm text-gray-600 leading-relaxed">{record.result?.summary || record.summary || '暂无评语'}</p>
              </div>
            </div>

            {/* Annotations */}
            <div className="bg-white rounded-2xl p-5 shadow-sm border border-gray-100">
              <h3 className="font-bold text-gray-800 mb-4 flex items-center gap-1.5">
                <AlertCircle className="w-4 h-4 text-orange-500" />
                逐句批改详情
              </h3>
              
              <div className="space-y-4">
                {record.result?.annotations?.map((ann: any, i: number) => {
                  const isHighlight = ann.type === 'highlight';
                  return (
                    <div key={i} className={`rounded-xl p-4 border ${isHighlight ? 'bg-blue-50 border-blue-100' : 'bg-gray-50 border-gray-100'}`}>
                      <div className={`mb-3 pb-3 border-b ${isHighlight ? 'border-blue-200/60' : 'border-gray-200/60'}`}>
                        <span className={`inline-block px-2 py-0.5 text-[10px] font-bold rounded mb-1 ${isHighlight ? 'bg-blue-200 text-blue-700' : 'bg-gray-200 text-gray-600'}`}>
                          {isHighlight ? '好句' : '原句'}
                        </span>
                        <p className="text-sm text-gray-700 font-medium">{ann.originalSentence}</p>
                      </div>
                      
                      <div className="flex flex-col gap-2">
                        {isHighlight ? (
                          <div className="flex gap-2 items-start">
                            <span className="inline-block px-2 py-0.5 bg-blue-100 text-blue-600 text-[10px] font-bold rounded mt-0.5 shrink-0">点评</span>
                            <p className="text-xs text-gray-600 leading-relaxed">{ann.reason}</p>
                          </div>
                        ) : (
                          <>
                            {ann.issue && (
                              <div className="flex gap-2 items-start">
                                <span className="inline-block px-2 py-0.5 bg-red-100 text-red-600 text-[10px] font-bold rounded mt-0.5 shrink-0">问题</span>
                                <p className="text-xs text-gray-600 leading-relaxed">{ann.issue}</p>
                              </div>
                            )}
                            {ann.suggestion && (
                              <div className="flex gap-2 items-start">
                                <span className="inline-block px-2 py-0.5 bg-orange-100 text-orange-600 text-[10px] font-bold rounded mt-0.5 shrink-0">建议</span>
                                <p className="text-xs text-gray-600 leading-relaxed">{ann.suggestion}</p>
                              </div>
                            )}
                            {ann.correctedSentence && (
                              <div className="flex gap-2 items-start">
                                <span className="inline-block px-2 py-0.5 bg-green-100 text-green-600 text-[10px] font-bold rounded mt-0.5 shrink-0">修改</span>
                                <p className="text-xs text-gray-600 leading-relaxed font-medium">{ann.correctedSentence}</p>
                              </div>
                            )}
                          </>
                        )}
                      </div>
                    </div>
                  );
                })}
              </div>
            </div>

            {/* Model Essay */}
            {record.result?.modelEssay && (
              <div className="bg-white rounded-2xl p-5 shadow-sm border border-gray-100">
                <h3 className="font-bold text-gray-800 mb-4 flex items-center gap-1.5">
                  <AlertCircle className="w-4 h-4 text-purple-500" />
                  修改后范文
                </h3>
                <div className="bg-purple-50/50 rounded-xl p-4 border border-purple-100">
                  <p className="text-sm text-gray-700 leading-relaxed whitespace-pre-wrap">
                    {record.result.modelEssay}
                  </p>
                </div>
              </div>
            )}
          </div>
        )}
      </div>
    </div>
  );
}

// src/pages/record-detail/index.vue
<template>
  <view class="detail-page">
    <!-- 顶部导航 -->
    <view class="nav-bar">
      <view class="nav-back" @click="goBack">
        <wd-icon name="arrow-left" size="44" color="#666666" />
      </view>
      <text class="nav-title">记录详情</text>
    </view>

    <view class="page-body">
      <!-- 不存在 -->
      <view v-if="!record" class="empty-state">
        <text class="empty-text">记录不存在或已被删除</text>
      </view>

      <!-- 帮写记录 -->
      <template v-else-if="record.type === 'write'">
        <view class="write-card">
          <text class="write-title">{{ record.title }}</text>
          <text class="write-date">{{ record.date }}</text>
          <rich-text :nodes="renderedWriteResult" class="write-content" />
        </view>
      </template>

      <!-- 批改记录 -->
      <template v-else>
        <!-- 分数卡 -->
        <view class="score-card">
          <view class="score-row">
            <view>
              <text class="score-label">学生姓名</text>
              <text class="score-name">{{ record.result?.studentName || '未知' }}</text>
            </view>
            <view class="score-right">
              <text class="score-label">最终得分</text>
              <view class="score-num-row">
                <text class="score-num">{{ record.result?.score || 0 }}</text>
                <text class="score-unit">分</text>
              </view>
            </view>
          </view>
          <view class="divider"></view>
          <view>
            <text class="comment-title">老师评语</text>
            <text class="comment-text">{{ record.result?.summary || record.summary || '暂无评语' }}</text>
          </view>
        </view>

        <!-- 逐句批改 -->
        <view class="annotations-card">
          <text class="section-title">逐句批改详情</text>
          <view class="ann-list">
            <view
              v-for="(ann, i) in record.result?.annotations"
              :key="i"
              :class="['ann-item', ann.type === 'highlight' ? 'ann-highlight' : 'ann-issue']"
            >
              <view class="ann-header">
                <text :class="['ann-tag', ann.type === 'highlight' ? 'tag-highlight' : 'tag-issue']">
                  {{ ann.type === 'highlight' ? '好句' : '原句' }}
                </text>
                <text class="ann-sentence">{{ ann.originalSentence }}</text>
              </view>
              <view class="ann-details">
                <template v-if="ann.type === 'highlight'">
                  <view class="detail-row">
                    <text class="detail-tag tag-comment">点评</text>
                    <text class="detail-text">{{ ann.reason }}</text>
                  </view>
                </template>
                <template v-else>
                  <view v-if="ann.issue" class="detail-row">
                    <text class="detail-tag tag-problem">问题</text>
                    <text class="detail-text">{{ ann.issue }}</text>
                  </view>
                  <view v-if="ann.suggestion" class="detail-row">
                    <text class="detail-tag tag-suggest">建议</text>
                    <text class="detail-text">{{ ann.suggestion }}</text>
                  </view>
                  <view v-if="ann.correctedSentence" class="detail-row">
                    <text class="detail-tag tag-fix">修改</text>
                    <text class="detail-text detail-bold">{{ ann.correctedSentence }}</text>
                  </view>
                </template>
              </view>
            </view>
          </view>
        </view>

        <!-- 范文 -->
        <view v-if="record.result?.modelEssay" class="essay-card">
          <text class="section-title">修改后范文</text>
          <view class="essay-content">
            <text class="essay-text">{{ record.result.modelEssay }}</text>
          </view>
        </view>
      </template>
    </view>
  </view>
</template>

<script setup>
import { useRecordStore } from '@/store/useRecordStore'

const recordStore = useRecordStore()

const recordId = ref('')
const record = computed(() => recordStore.getRecordById(recordId.value))

const renderedWriteResult = computed(() => {
  const text = record.value?.result || ''
  const escaped = text
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/\n/g, '<br/>')
  return `<div style="font-size:28rpx;color:#333;line-height:1.8;">${escaped}</div>`
})

onLoad((options) => {
  recordId.value = options.id || ''
})

const goBack = () => {
  uni.navigateBack()
}
</script>

<style scoped lang="scss">
.detail-page {
  min-height: 100vh;
  background: #f5f5f5;
}

.nav-bar {
  background: #ffffff;
  padding: 80rpx 32rpx 24rpx;
  display: flex;
  align-items: center;
  box-shadow: 0 2rpx 8rpx rgba(0, 0, 0, 0.04);
  position: sticky;
  top: 0;
  z-index: 10;
}

.nav-back {
  padding: 8rpx;
  margin-left: -16rpx;
}

.nav-title {
  font-size: 34rpx;
  font-weight: bold;
  color: #333333;
  flex: 1;
  text-align: center;
  margin-right: 60rpx;
}

.page-body {
  padding: 24rpx 32rpx 40rpx;
  display: flex;
  flex-direction: column;
  gap: 20rpx;
}

.empty-state {
  display: flex;
  align-items: center;
  justify-content: center;
  padding-top: 200rpx;
}

.empty-text {
  font-size: 28rpx;
  color: #cccccc;
}

/* 帮写样式 */
.write-card {
  background: #ffffff;
  border-radius: 24rpx;
  padding: 36rpx;
}

.write-title {
  font-size: 30rpx;
  font-weight: bold;
  color: #333333;
  display: block;
  margin-bottom: 8rpx;
}

.write-date {
  font-size: 22rpx;
  color: #cccccc;
  display: block;
  margin-bottom: 24rpx;
}

.write-content {
  font-size: 28rpx;
  color: #333333;
  line-height: 1.8;
}

/* 批改结果样式 */
.score-card {
  background: #ffffff;
  border-radius: 24rpx;
  padding: 40rpx;
  position: relative;
  overflow: hidden;
}

.score-row {
  display: flex;
  justify-content: space-between;
  align-items: flex-start;
}

.score-label {
  font-size: 24rpx;
  color: #999999;
  display: block;
}

.score-name {
  font-size: 36rpx;
  font-weight: bold;
  color: #333333;
  display: block;
  margin-top: 8rpx;
}

.score-right {
  text-align: right;
}

.score-num-row {
  display: flex;
  align-items: baseline;
  gap: 4rpx;
  color: #f97316;
  justify-content: flex-end;
}

.score-num {
  font-size: 72rpx;
  font-weight: 900;
}

.score-unit {
  font-size: 24rpx;
  font-weight: bold;
}

.divider {
  height: 2rpx;
  background: #f5f5f5;
  margin: 28rpx 0;
}

.comment-title {
  font-size: 26rpx;
  font-weight: bold;
  color: #333333;
  display: block;
  margin-bottom: 12rpx;
}

.comment-text {
  font-size: 26rpx;
  color: #666666;
  line-height: 1.8;
  display: block;
}

.annotations-card {
  background: #ffffff;
  border-radius: 24rpx;
  padding: 32rpx;
}

.section-title {
  font-size: 28rpx;
  font-weight: bold;
  color: #333333;
  display: block;
  margin-bottom: 24rpx;
}

.ann-list {
  display: flex;
  flex-direction: column;
  gap: 20rpx;
}

.ann-item {
  border-radius: 20rpx;
  padding: 24rpx;
  border: 2rpx solid;
}

.ann-highlight {
  background: #eff6ff;
  border-color: #dbeafe;
}

.ann-issue {
  background: #f9fafb;
  border-color: #f3f4f6;
}

.ann-header {
  padding-bottom: 16rpx;
  margin-bottom: 16rpx;
  border-bottom: 2rpx solid rgba(0, 0, 0, 0.06);
}

.ann-tag {
  display: inline-block;
  padding: 2rpx 12rpx;
  font-size: 18rpx;
  font-weight: bold;
  border-radius: 6rpx;
  margin-bottom: 8rpx;
}

.tag-highlight {
  background: #bfdbfe;
  color: #1d4ed8;
}

.tag-issue {
  background: #e5e7eb;
  color: #4b5563;
}

.ann-sentence {
  font-size: 26rpx;
  color: #333333;
  font-weight: 500;
  display: block;
}

.ann-details {
  display: flex;
  flex-direction: column;
  gap: 12rpx;
}

.detail-row {
  display: flex;
  gap: 12rpx;
  align-items: flex-start;
}

.detail-tag {
  display: inline-block;
  padding: 2rpx 12rpx;
  font-size: 18rpx;
  font-weight: bold;
  border-radius: 6rpx;
  flex-shrink: 0;
  margin-top: 4rpx;
}

.tag-comment {
  background: #dbeafe;
  color: #2563eb;
}

.tag-problem {
  background: #fee2e2;
  color: #dc2626;
}

.tag-suggest {
  background: #fef3c7;
  color: #d97706;
}

.tag-fix {
  background: #d1fae5;
  color: #059669;
}

.detail-text {
  font-size: 22rpx;
  color: #666666;
  line-height: 1.6;
  flex: 1;
}

.detail-bold {
  font-weight: 500;
}

.essay-card {
  background: #ffffff;
  border-radius: 24rpx;
  padding: 32rpx;
}

.essay-content {
  background: #faf5ff;
  border-radius: 20rpx;
  padding: 28rpx;
  border: 2rpx solid #e9d5ff;
}

.essay-text {
  font-size: 26rpx;
  color: #333333;
  line-height: 1.8;
  white-space: pre-wrap;
}
</style>
